"""add app_settings table

Revision ID: 23aa94f7d34e
Revises: bc2cf87d8334
Create Date: 2026-10-01 09:24:30.803494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23aa94f7d34e'
down_revision: Union[str, Sequence[str], None] = 'bc2cf87d8334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('default_monthly_analysis_limit', sa.Integer(), nullable=True),
    sa.Column('default_monthly_chat_limit', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name='app_settings_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
