"""add investment_preferences table

Revision ID: 68dc176b943a
Revises: c563e78c78d0
Create Date: 2026-09-25 15:27:58.449992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68dc176b943a'
down_revision: Union[str, Sequence[str], None] = 'c563e78c78d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
    sa.Column('sector_avoid_list', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_preferences_user_id'), 'investment_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_preferences_user_id'), table_name='investment_preferences')
    op.drop_table('investment_preferences')
    # ### end Alembic commands ###
