"""add evidence fields to recommendations

Revision ID: 82b443a1ddde
Revises: 73809764e6a1
Create Date: 2026-09-29 21:57:55.390450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b443a1ddde'
down_revision: Union[str, Sequence[str], None] = '73809764e6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('fundamental_score', sa.Integer(), nullable=True))
    op.add_column('recommendations', sa.Column('technical_signal', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'technical_signal')
    op.drop_column('recommendations', 'fundamental_score')
    # ### end Alembic commands ###
