"""add recommendation memory columns

Revision ID: c563e78c78d0
Revises: 5af8cb330a2c
Create Date: 2026-09-24 16:56:23.607458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = 'c563e78c78d0'
down_revision: Union[str, Sequence[str], None] = '5af8cb330a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('price_at_recommendation', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('recommendations', sa.Column('outcome_forward_return_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('recommendations', sa.Column('outcome_evaluated_at', sa.DateTime(), nullable=True))
    op.add_column('recommendations', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'embedding')
    op.drop_column('recommendations', 'outcome_evaluated_at')
    op.drop_column('recommendations', 'outcome_forward_return_pct')
    op.drop_column('recommendations', 'price_at_recommendation')
    # ### end Alembic commands ###
